### ISSUE TITLE
Невозможно подключиться к Oracle DB

### ISSUE THREAD

**Issue by das13** [bobnewmark/Lab3Group1#6]
При попытке подключения приложения к БД Oracle получаем ошибку:

> org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: Could not open connection

Судя по конфигурации, в приложении есть ссылки на драйвер MySql.

**Comment by bobnewmark** [comment]
Мавен не подгружает ojdbc драйвер, ошибка возникает из-за отсутствия драйвера, который следует поместить в classpath либо проинсталлировать в репозиторий мавена вручную.
